[package]
name = "baf_bin"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
baf = { path = "../crate-lib" }
clap = { version = "4.5.54", features = ["derive"] }
walkdir = "2.5.0"
